### ISSUE TITLE
Issue with load.homologs()

### ISSUE THREAD

**Issue by Al-Murphy** [NathanSkene/One2One#3]
In load.homologs(), the following line:

```
# The table is badly formatted, so drop rubbish
hom_vert = suppressWarnings(hom_vert[!is.na(as.numeric(hom_vert$`HomoloGene ID`)),])
```

Now removes all data from the downloaded file: "http://www.informatics.jax.org/downloads/reports/HOM_AllOrganism.rpt"

This was noted here: https://github.com/NathanSkene/MAGMA_Celltyping/issues/42 . This is causing a runtime failure in MAGMA_celltyping

The issue is caused because the column HomoloGene ID no longer exists. The new column names are:

```
[1] "DB Class Key"                           "Common Organism Name"                  
 [3] "NCBI Taxon ID"                          "Symbol"                                
 [5] "EntrezGene ID"                          "Mouse MGI ID"                          
 [7] "HGNC ID"                                "OMIM Gene ID"                          
 [9] "Genetic Location"                       "Genomic Coordinates (mouse: , human: )"
[11] "Name"                                   "Synonyms"  
```

@NathanSkene can you confirm but perhaps there has just been a name change for this column? This nomenclature will need to be updated throughout the package. I will do this and push the change once you confirm.

Thanks!

**Comment by Al-Murphy** [comment]
Effected functions are analyse.orthology() and load.homologs()

**Comment by NathanSkene** [comment]
Don't think it would be Taxon ID... think that relates to species

I've attached a copy of the old version of the file.

[Uploading HOM_AllOrganism.rpt.txt.zip…]()

Perhaps it's `DB Class Key`?

Might be best to depreciate usage of the One2One package... Brian had figured out a new way of doing it more generically using some other package?

**Comment by NathanSkene** [comment]
[HOM_AllOrganism.rpt.txt.zip](https://github.com/NathanSkene/One2One/files/6800774/HOM_AllOrganism.rpt.txt.zip)

**Comment by Al-Murphy** [comment]
It looks like its `DB Class Key` that has been renamed from `HomoloGene ID`. However, excluding the naming difference, the old database appeared to have a lot more data:

```
> dim(hom_vert[!is.na(as.numeric(hom_vert$`DB Class Key`)),])
[1] 83484    12
> dim(hom_vert2[!is.na(as.numeric(hom_vert$`DB Class Key`)),])
[1] 187079     12
```

In the short term, will we just go with this new dataset despite the smaller size? Or can we put the old dataset somewhere we can pull by url in the package (even the URL to the dataset you attached here)?

I agree changing away from it in the long run is a good idea. Did Brian add this approach to his current MAGMA_celltyping version (github won't let me tag Brian to this issue for some reason)?

**Comment by kvshams** [comment]
@Al-Murphy.. Hmm that might be the reason I am seeing a difference in the association by using old and new version. I was wondering what went wrong!

**Comment by Al-Murphy** [comment]
Issue is fixed, reverted to the original HOM_AllOrganism.rpt.txt.zip file
